//! Application state shared across all API handlers and the bot pipeline.
//!
//! `AppState` is the single source of truth for the bot's runtime state:
//! mode (stopped/paper/live), positions, signals, metrics, strategies, config,
//! and the bankroll ladder. It is wrapped in `Arc<AppState>` and passed as
//! axum state to all route handlers.
//!
//! All mutable fields use `std::sync::RwLock` (not tokio RwLock) because:
//! 1. Lock hold times are very short (microseconds for reads, milliseconds for writes).
//! 2. Both sync (pipeline) and async (API handlers) code needs access.
//! 3. std RwLock is simpler and does not require `.await` for lock acquisition.

use std::sync::RwLock;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;
use polybot_risk::types::RiskConfig;
use polybot_scanner::crypto::CryptoRound;

/// Operating mode of the bot. Transitions are controlled via POST /start and /stop.
///
/// - `Stopped`: pipeline is idle, no scanning or trading.
/// - `Paper`: pipeline runs, signals are generated, but trades are simulated (no real money).
/// - `Live`: pipeline runs with real ECDSA-signed orders on Polymarket CLOB.
///   Requires explicit `confirm_live: true` and API key secrets to activate.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum BotMode {
    Stopped,
    Paper,
    Live,
}

/// A trading signal generated by the pipeline for a specific market/round.
///
/// Signals capture the decision point: what the strategy predicted, whether risk
/// gates approved, and whether a trade was executed. Stored for audit trail and
/// displayed in the frontend signal log.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Unique signal ID (UUID).
    pub id: String,
    /// When the signal was generated.
    pub timestamp: DateTime<Utc>,
    /// Polymarket market/condition ID.
    pub market_id: String,
    /// Human-readable market question (e.g. "Will BTC go Up in 5m?").
    pub question: String,
    /// Computed edge: confidence * |p_up - market_price_up|.
    pub edge: f64,
    /// Z-score of the displacement signal (from the strategy).
    pub z_score: f64,
    /// What happened to this signal: entered, rejected, skipped, or exited.
    pub action: SignalAction,
    /// Human-readable explanation of why this action was taken.
    pub reason: String,
}

/// What action was taken on a trading signal.
///
/// - `Entered`: trade was executed (paper or live).
/// - `Rejected`: risk gate blocked the trade (exposure limit, drawdown, etc.).
/// - `Skipped`: strategy chose not to trade (low confidence, insufficient data).
/// - `Exited`: an existing position was closed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SignalAction {
    Entered,
    Rejected,
    Skipped,
    Exited,
}

/// An active or closed trading position on a Polymarket binary outcome market.
///
/// Positions track entry conditions, current P&L, and exit metadata. When a
/// position is closed (round resolves or stop-loss triggers), it moves from
/// the active positions list to the closed positions list in AppState.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    /// Unique position ID (UUID).
    pub id: String,
    pub market_id: String,
    pub question: String,
    pub direction: String,
    pub entry_price: f64,
    pub current_price: f64,
    pub size: f64,
    pub unrealized_pnl: f64,
    pub opened_at: DateTime<Utc>,
    pub entry_edge: f64,
    #[serde(default)]
    pub is_live: bool,
    #[serde(default)]
    pub fee_rate_bps: f64,
    #[serde(default)]
    pub hold_to_resolution: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_reason: Option<String>,
}

/// Aggregate performance metrics for a pipeline.
///
/// Maintained separately for the general pipeline and the crypto HF pipeline.
/// Updated after each trade close. The equity curve is an append-only list of
/// cumulative P&L after each trade.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BotMetrics {
    pub total_trades: u64,
    pub wins: u64,
    pub losses: u64,
    pub win_rate: f64,
    pub sharpe_ratio: f64,
    pub max_drawdown: f64,
    pub profit_factor: f64,
    pub total_pnl: f64,
    pub equity_curve: Vec<f64>,
    #[serde(default)]
    pub up_predictions: u64,
    #[serde(default)]
    pub down_predictions: u64,
}

/// Pipeline latency metrics, tracked per stage.
///
/// Each stage (scan, risk, execute) has average and P99 latency in milliseconds.
/// Updated by the pipeline after each cycle. Used by the frontend latency dashboard
/// to detect performance degradation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LatencyMetrics {
    pub scan_avg_ms: f64,
    pub scan_p99_ms: f64,
    pub risk_avg_ms: f64,
    pub risk_p99_ms: f64,
    pub execute_avg_ms: f64,
    pub execute_p99_ms: f64,
    pub total_avg_ms: f64,
    pub total_p99_ms: f64,
}

/// Configuration for a single strategy: name, enabled flag, and ensemble weight.
///
/// Strategies can be toggled on/off and have their weights adjusted at runtime
/// via the API (PUT /strategies). The weight determines how much influence a
/// strategy's prediction has in the ensemble combination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    /// Strategy name, must match the registered name in Python strategy service.
    pub name: String,
    /// Whether this strategy is active for the current pipeline.
    pub enabled: bool,
    /// Ensemble weight. Higher = more influence on the combined prediction.
    pub weight: f64,
}

impl StrategyConfig {
    /// Default strategy configuration for the general (non-crypto) pipeline.
    ///
    /// Hardcoded weights reflect empirical performance ranking:
    /// - arbitrage (2.0): strongest non-candle signal
    /// - spread (1.5), calibration_fader (1.5): moderate performers
    /// - liquidity_edge (1.0), volume_momentum (1.0): supplementary
    /// - mean_reversion (0.5): weakest, kept for diversification
    pub fn defaults() -> Vec<Self> {
        vec![
            Self { name: "mean_reversion".into(), enabled: true, weight: 0.5 },
            Self { name: "arbitrage".into(), enabled: true, weight: 2.0 },
            Self { name: "liquidity_edge".into(), enabled: true, weight: 1.0 },
            Self { name: "spread".into(), enabled: true, weight: 1.5 },
            Self { name: "calibration_fader".into(), enabled: true, weight: 1.5 },
            Self { name: "volume_momentum".into(), enabled: true, weight: 1.0 },
        ]
    }
}

/// Central application state shared across all API handlers and pipeline tasks.
///
/// All mutable fields are wrapped in `std::sync::RwLock` for thread-safe access.
/// The state is split into two logical sections:
///
/// 1. **General pipeline state**: `mode`, `config`, `strategies`, `signals`,
///    `positions`, `closed_positions`, `metrics`, `latency`.
/// 2. **Crypto HF pipeline state**: `crypto_rounds`, `crypto_positions`,
///    `crypto_closed`, `crypto_signals`, `crypto_metrics`, `crypto_strategies`.
///
/// This split exists because the bot originally supported two pipeline modes
/// (general Polymarket + crypto high-frequency). The crypto pipeline is the
/// primary one in current deployment.
pub struct AppState {
    /// Current operating mode: Stopped, Paper, or Live.
    pub mode: RwLock<BotMode>,
    pub started_at: RwLock<Option<DateTime<Utc>>>,
    pub config: RwLock<RiskConfig>,
    pub strategies: RwLock<Vec<StrategyConfig>>,
    pub signals: RwLock<Vec<Signal>>,
    pub positions: RwLock<Vec<Position>>,
    pub closed_positions: RwLock<Vec<Position>>,
    pub metrics: RwLock<BotMetrics>,
    pub latency: RwLock<LatencyMetrics>,
    pub initial_bankroll: f64,
    pub tx: broadcast::Sender<String>,
    // Instance identification
    pub instance_name: String,
    pub strategy_profile: String,
    // Crypto pipeline state
    pub crypto_rounds: RwLock<Vec<CryptoRound>>,
    pub crypto_positions: RwLock<Vec<Position>>,
    pub crypto_closed: RwLock<Vec<Position>>,
    pub crypto_signals: RwLock<Vec<Signal>>,
    pub crypto_metrics: RwLock<BotMetrics>,
    pub crypto_cycle_speed_ms: RwLock<u64>,
    pub crypto_nearest_expiry: RwLock<i64>,
    pub pipeline_mode: RwLock<PipelineMode>,
    pub crypto_strategies: RwLock<Vec<StrategyConfig>>,
    pub db: Option<std::sync::Arc<crate::db::Database>>,
    pub ladder: RwLock<BankrollLadder>,
}

// === Bankroll Ladder ===
// The ladder is a conservative bankroll growth strategy that locks profits
// progressively. Starting from a seed amount, each "round" targets 2x the
// available capital as profit. When achieved, half the profit is locked
// (protected from future losses) and half becomes the new trading capital.
// This continues until the available capital reaches the aggressive cap,
// after which all profits go to locked.

/// A single round (milestone) in the bankroll ladder.
///
/// Each round starts with a target P&L, available trading capital, and locked
/// capital. When total P&L crosses the target, the round completes and the
/// next round begins with updated capital allocation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LadderRound {
    pub round: u32,
    pub target_pnl: f64,
    pub locked: f64,
    pub available: f64,
    pub started_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<i64>,
    pub trades_in_round: u64,
}

/// Bankroll ladder: progressive profit-locking growth strategy.
///
/// The ladder doubles the available trading capital each round while locking
/// half the profits. This protects early gains while allowing exponential
/// growth of the trading account.
///
/// # Example progression (seed=$500, cap=$10,000)
/// - R0: available=$500, target profit=$1,000. On hit: lock $500+$500=$1,000, avail=$500.
/// - R1: available=$500, target=$1,000. On hit: lock +$500, avail=$1,000.
/// - R2: available=$1,000, target=$2,000. On hit: lock +$1,000, avail=$2,000.
/// - ...continues doubling until available reaches $10,000 (aggressive cap).
/// - Post-cap: available stays at $10,000, all profit goes to locked.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BankrollLadder {
    /// Initial seed capital used to start the ladder.
    pub seed: f64,
    /// Maximum trading capital. Once reached, available stops growing.
    /// Hardcoded default: $10,000 (overridable via AGGRESSIVE_CAP env var).
    pub aggressive_cap: f64,
    pub current_round: u32,
    pub locked: f64,
    pub available: f64,
    pub cumulative_target: f64,
    pub total_profit: f64,
    pub rounds: Vec<LadderRound>,
}

impl BankrollLadder {
    /// Create a new ladder starting from the given seed capital.
    ///
    /// R0 starts with the full seed as available capital and targets 2x seed
    /// as cumulative profit. The aggressive cap defaults to $10,000 but can
    /// be overridden via the AGGRESSIVE_CAP environment variable.
    pub fn new(seed: f64) -> Self {
        let aggressive_cap: f64 = std::env::var("AGGRESSIVE_CAP")
            .ok().and_then(|v| v.parse().ok()).unwrap_or(10_000.0);
        // R0: trade with seed, target = 2× seed profit.
        // After R0: seed locked, available = profit/2.
        // Each subsequent round: target = 2× available, lock half, free half.
        // Available doubles each round until capped.
        Self {
            seed,
            aggressive_cap,
            current_round: 0,
            locked: 0.0,
            available: seed,
            cumulative_target: 2.0 * seed, // R0 target: earn 2× seed
            total_profit: 0.0,
            rounds: vec![LadderRound {
                round: 0,
                target_pnl: 2.0 * seed,
                locked: 0.0,
                available: seed,
                started_at: Utc::now(),
                completed_at: None,
                duration_secs: None,
                trades_in_round: 0,
            }],
        }
    }

    /// Check if total_pnl crossed the next milestone; advance round if so.
    /// Returns true if a round was completed.
    ///
    /// Ladder logic:
    ///   R0: seed=$500, target profit=$1000 (2×seed). On complete: lock seed+$500, avail=$500.
    ///   RN: target profit = 2×available. On complete: lock half, free half. Available doubles.
    ///   Cap: available maxes at aggressive_cap ($10k). At cap: locked=$10,500.
    pub fn check_milestone(&mut self, total_pnl: f64, total_trades: u64) -> bool {
        self.total_profit = total_pnl;

        // Update current round's trade count
        let prev_trades: u64 = self.rounds.iter()
            .rev().skip(1)
            .map(|r| r.trades_in_round)
            .sum();
        if let Some(current) = self.rounds.last_mut() {
            current.trades_in_round = total_trades.saturating_sub(prev_trades);
        }

        if total_pnl >= self.cumulative_target {
            let now = Utc::now();
            // Complete current round
            if let Some(current) = self.rounds.last_mut() {
                current.completed_at = Some(now);
                current.duration_secs = Some((now - current.started_at).num_seconds());
            }

            let at_cap = self.available >= self.aggressive_cap;

            if at_cap {
                // Post-cap: all profit goes to locked, available stays fixed
                let round_profit = 2.0 * self.available;
                self.locked += round_profit;
            } else {
                // Pre-cap: split profit — lock half, free half
                let round_profit = 2.0 * self.available;
                let lock_half = round_profit / 2.0;
                let free_half = round_profit / 2.0;

                if self.current_round == 0 {
                    // R0 special: lock seed + half profit
                    self.locked = self.seed + lock_half;
                    self.available = free_half;
                } else {
                    self.locked += lock_half;
                    let new_available = self.available + free_half;
                    if new_available > self.aggressive_cap {
                        let excess = new_available - self.aggressive_cap;
                        self.locked += excess;
                        self.available = self.aggressive_cap;
                    } else {
                        self.available = new_available;
                    }
                }
            }

            self.current_round += 1;

            // Compute next round's target
            let next_round_profit = if self.available >= self.aggressive_cap {
                // Post-cap: target = 2× available (all goes to locked)
                2.0 * self.available
            } else {
                // Pre-cap: 2× available, or less if approaching cap
                let uncapped = 2.0 * self.available;
                let needed_for_cap = (self.aggressive_cap - self.available) * 2.0;
                uncapped.min(needed_for_cap)
            };
            self.cumulative_target += next_round_profit;

            self.rounds.push(LadderRound {
                round: self.current_round,
                target_pnl: self.cumulative_target,
                locked: self.locked,
                available: self.available,
                started_at: now,
                completed_at: None,
                duration_secs: None,
                trades_in_round: 0,
            });
            return true;
        }
        false
    }
}

/// Which pipeline(s) to run: both, crypto-only, or general-only.
///
/// - `Both`: run both the general Polymarket pipeline and the crypto HF pipeline.
/// - `CryptoOnly` ("crypto_hf"): only run the crypto high-frequency pipeline.
/// - `GeneralOnly` ("general_lf"): only run the general low-frequency pipeline.
///
/// The crypto pipeline is the primary one in current deployment. The general
/// pipeline exists for future expansion to non-crypto Polymarket markets.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PipelineMode {
    Both,
    #[serde(rename = "crypto_hf")]
    CryptoOnly,
    #[serde(rename = "general_lf")]
    GeneralOnly,
}

impl AppState {
    /// Create AppState with default bankroll ($10,000).
    /// Convenience constructor for tests and single-instance deployments.
    pub fn new() -> Self {
        Self::new_with_bankroll(10_000.0)
    }

    /// Create AppState with a custom bankroll amount.
    /// Risk config limits are scaled proportionally to the bankroll.
    pub fn new_with_bankroll(bankroll: f64) -> Self {
        Self::new_with_params(bankroll, "default".into(), "baseline".into())
    }

    /// Full constructor with all parameters.
    ///
    /// # Arguments
    /// * `bankroll` - Starting capital. Risk limits scale with this value.
    /// * `instance_name` - Human-readable name for this bot instance (used in logs/API).
    /// * `strategy_profile` - Which Python strategy profile to use (e.g. "garch-t", "fair-value").
    ///
    /// # Hardcoded values and their rationale
    /// * `max_exposure_per_position`: 20% of bankroll, capped at $1,000.
    ///   Prevents any single trade from risking too much capital.
    /// * `max_total_exposure`: 80% of bankroll, capped at $5,000.
    ///   Keeps a cash reserve for fee payments and drawdown buffer.
    /// * `var_limit_95`: 10% of bankroll, capped at $500.
    ///   95th percentile Value-at-Risk limit for the portfolio.
    /// * `kelly_fraction`: 0.25 (quarter-Kelly). Full Kelly is too aggressive
    ///   for binary outcome markets where model uncertainty is high.
    ///   Overridable via KELLY_FRACTION env var.
    /// * `mdd_limit`: 0.25 (25% max drawdown). Overridable via MAX_DRAWDOWN_PCT.
    /// * Broadcast channel capacity: 100 messages. Chosen to handle burst of
    ///   WebSocket clients without dropping messages during normal operation.
    /// * Default crypto strategies and their weights reflect the empirical
    ///   signal ranking from production testing:
    ///   - time_decay_lock (3.0): strongest Rust-side signal
    ///   - candle_trend (2.5): proven displacement z-score
    ///   - vol_regime (2.0): Kaufman ER regime detection
    ///   - volume_breakout (1.5): volume-confirmed displacement
    ///   - cross_asset_momentum (1.0): weakest, supplementary
    pub fn new_with_params(bankroll: f64, instance_name: String, strategy_profile: String) -> Self {
        let (tx, _) = broadcast::channel(100);
        // Read kelly_fraction from env, default 0.25
        let kelly_fraction: f64 = std::env::var("KELLY_FRACTION")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(0.25);
        let mdd_limit: f64 = std::env::var("MAX_DRAWDOWN_PCT")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(0.25);
        // Scale risk config to bankroll
        let config = RiskConfig {
            max_exposure_per_position: (bankroll * 0.2).min(1000.0),
            max_total_exposure: (bankroll * 0.8).min(5000.0),
            var_limit_95: (bankroll * 0.1).min(500.0),
            kelly_fraction,
            mdd_limit,
            ..RiskConfig::default()
        };
        Self {
            mode: RwLock::new(BotMode::Stopped),
            started_at: RwLock::new(None),
            config: RwLock::new(config),
            strategies: RwLock::new(StrategyConfig::defaults()),
            signals: RwLock::new(Vec::new()),
            positions: RwLock::new(Vec::new()),
            closed_positions: RwLock::new(Vec::new()),
            metrics: RwLock::new(BotMetrics {
                total_trades: 0, wins: 0, losses: 0, win_rate: 0.0,
                sharpe_ratio: 0.0, max_drawdown: 0.0, profit_factor: 0.0,
                total_pnl: 0.0, equity_curve: Vec::new(),
                up_predictions: 0, down_predictions: 0,
            }),
            latency: RwLock::new(LatencyMetrics {
                scan_avg_ms: 0.0, scan_p99_ms: 0.0,
                risk_avg_ms: 0.0, risk_p99_ms: 0.0,
                execute_avg_ms: 0.0, execute_p99_ms: 0.0,
                total_avg_ms: 0.0, total_p99_ms: 0.0,
            }),
            initial_bankroll: bankroll,
            tx,
            instance_name,
            strategy_profile,
            crypto_rounds: RwLock::new(Vec::new()),
            crypto_positions: RwLock::new(Vec::new()),
            crypto_closed: RwLock::new(Vec::new()),
            crypto_signals: RwLock::new(Vec::new()),
            crypto_metrics: RwLock::new(BotMetrics {
                total_trades: 0, wins: 0, losses: 0, win_rate: 0.0,
                sharpe_ratio: 0.0, max_drawdown: 0.0, profit_factor: 0.0,
                total_pnl: 0.0, equity_curve: Vec::new(),
                up_predictions: 0, down_predictions: 0,
            }),
            crypto_cycle_speed_ms: RwLock::new(5000),
            crypto_nearest_expiry: RwLock::new(0),
            pipeline_mode: RwLock::new(PipelineMode::Both),
            crypto_strategies: RwLock::new(vec![
                StrategyConfig { name: "time_decay_lock".into(), enabled: true, weight: 3.0 },
                StrategyConfig { name: "candle_trend".into(), enabled: true, weight: 2.5 },
                StrategyConfig { name: "vol_regime".into(), enabled: true, weight: 2.0 },
                StrategyConfig { name: "volume_breakout".into(), enabled: true, weight: 1.5 },
                StrategyConfig { name: "cross_asset_momentum".into(), enabled: true, weight: 1.0 },
            ]),
            db: None,
            ladder: RwLock::new(BankrollLadder::new(
                std::env::var("LADDER_UNIT").ok().and_then(|v| v.parse().ok()).unwrap_or(bankroll)
            )),
        }
    }
}
